// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT
// Generated by Playforce 2025-06-13T20:17:06.790Z

export const objectType = "Case";

export interface Case {
	AccountId?:string                                           // reference       "Account ID"              ReferenceTo => Account
	AssetId?:string                                             // reference       "Asset ID"                ReferenceTo => Asset
	CaseNumber?:string                                          // string          "Case Number"             
	ClosedDate?:string                                          // datetime        "Closed Date"             
	Comments?:string                                            // textarea        "Internal Comments"       
	ContactEmail?:string                                        // email           "Contact Email"           
	ContactFax?:string                                          // phone           "Contact Fax"             
	ContactId?:string                                           // reference       "Contact ID"              ReferenceTo => Contact
	ContactMobile?:string                                       // phone           "Contact Mobile"          
	ContactPhone?:string                                        // phone           "Contact Phone"           
	CreatedById?:string                                         // reference       "Created By ID"           ReferenceTo => User
	CreatedDate?:string                                         // datetime        "Created Date"            
	Description?:string                                         // textarea        "Description"             
	EngineeringReqNumber__c?:string                             // string          "Engineering Req Number"  
	Id?:string                                                  // id              "Case ID"                 
	IsClosed?:boolean                                           // boolean         "Closed"                  
	IsDeleted?:boolean                                          // boolean         "Deleted"                 
	IsEscalated?:boolean                                        // boolean         "Escalated"               
	LastModifiedById?:string                                    // reference       "Last Modified By ID"     ReferenceTo => User
	LastModifiedDate?:string                                    // datetime        "Last Modified Date"      
	LastReferencedDate?:string                                  // datetime        "Last Referenced Date"    
	LastViewedDate?:string                                      // datetime        "Last Viewed Date"        
	MasterRecordId?:string                                      // reference       "Master Record ID"        ReferenceTo => Case
	Origin?:string                                              // picklist        "Case Origin"             
	OwnerId?:string                                             // reference       "Owner ID"                ReferenceTo => Group
	ParentId?:string                                            // reference       "Parent Case ID"          ReferenceTo => Case
	PotentialLiability__c?:string                               // picklist        "Potential Liability"     
	Priority?:string                                            // picklist        "Priority"                
	Product__c?:string                                          // picklist        "Product"                 
	Reason?:string                                              // picklist        "Case Reason"             
	SLAViolation__c?:string                                     // picklist        "SLA Violation"           
	Status?:string                                              // picklist        "Status"                  
	Subject?:string                                             // string          "Subject"                 
	SuppliedCompany?:string                                     // string          "Company"                 
	SuppliedEmail?:string                                       // email           "Email Address"           
	SuppliedName?:string                                        // string          "Name"                    
	SuppliedPhone?:string                                       // string          "Phone"                   
	SystemModstamp?:string                                      // datetime        "System Modstamp"         
	Type?:string                                                // picklist        "Case Type"               
}

export const Case = {
	AccountId: "AccountId",                                     // reference       "Account ID"              ReferenceTo => Account
	AssetId: "AssetId",                                         // reference       "Asset ID"                ReferenceTo => Asset
	CaseNumber: "CaseNumber",                                   // string          "Case Number"             
	ClosedDate: "ClosedDate",                                   // datetime        "Closed Date"             
	Comments: "Comments",                                       // textarea        "Internal Comments"       
	ContactEmail: "ContactEmail",                               // email           "Contact Email"           
	ContactFax: "ContactFax",                                   // phone           "Contact Fax"             
	ContactId: "ContactId",                                     // reference       "Contact ID"              ReferenceTo => Contact
	ContactMobile: "ContactMobile",                             // phone           "Contact Mobile"          
	ContactPhone: "ContactPhone",                               // phone           "Contact Phone"           
	CreatedById: "CreatedById",                                 // reference       "Created By ID"           ReferenceTo => User
	CreatedDate: "CreatedDate",                                 // datetime        "Created Date"            
	Description: "Description",                                 // textarea        "Description"             
	EngineeringReqNumber__c: "EngineeringReqNumber__c",         // string          "Engineering Req Number"  
	Id: "Id",                                                   // id              "Case ID"                 
	IsClosed: "IsClosed",                                       // boolean         "Closed"                  
	IsDeleted: "IsDeleted",                                     // boolean         "Deleted"                 
	IsEscalated: "IsEscalated",                                 // boolean         "Escalated"               
	LastModifiedById: "LastModifiedById",                       // reference       "Last Modified By ID"     ReferenceTo => User
	LastModifiedDate: "LastModifiedDate",                       // datetime        "Last Modified Date"      
	LastReferencedDate: "LastReferencedDate",                   // datetime        "Last Referenced Date"    
	LastViewedDate: "LastViewedDate",                           // datetime        "Last Viewed Date"        
	MasterRecordId: "MasterRecordId",                           // reference       "Master Record ID"        ReferenceTo => Case
	Origin: "Origin",                                           // picklist        "Case Origin"             
	OwnerId: "OwnerId",                                         // reference       "Owner ID"                ReferenceTo => Group
	ParentId: "ParentId",                                       // reference       "Parent Case ID"          ReferenceTo => Case
	PotentialLiability__c: "PotentialLiability__c",             // picklist        "Potential Liability"     
	Priority: "Priority",                                       // picklist        "Priority"                
	Product__c: "Product__c",                                   // picklist        "Product"                 
	Reason: "Reason",                                           // picklist        "Case Reason"             
	SLAViolation__c: "SLAViolation__c",                         // picklist        "SLA Violation"           
	Status: "Status",                                           // picklist        "Status"                  
	Subject: "Subject",                                         // string          "Subject"                 
	SuppliedCompany: "SuppliedCompany",                         // string          "Company"                 
	SuppliedEmail: "SuppliedEmail",                             // email           "Email Address"           
	SuppliedName: "SuppliedName",                               // string          "Name"                    
	SuppliedPhone: "SuppliedPhone",                             // string          "Phone"                   
	SystemModstamp: "SystemModstamp",                           // datetime        "System Modstamp"         
	Type: "Type",                                               // picklist        "Case Type"               
};

