// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT
// Generated by Playforce 2025-06-13T20:17:06.790Z

import { AccountBase, accountMethods } from './salesforce/Account';
import { CaseBase, caseMethods } from './salesforce/Case';
import { ContactBase, contactMethods } from './salesforce/Contact';

/**
 * Request operations on the listed Salesforce objects.
 */

export const SalesforceRequests = {
   Account: { ...AccountBase, ...accountMethods(AccountBase)},
   Case: { ...CaseBase, ...caseMethods(CaseBase)},
   Contact: { ...ContactBase, ...contactMethods(ContactBase)},
};
