// Generated by generateSalesforceObjects 2025-05-26T10:09:18.861Z
    
import { createTypedSalesforceObject, SalesforceObjectInterface } from 'playforce';
import { Case, objectType } from './defs/objects/Case.def';
export { Case, objectType };

export const CaseBase = createTypedSalesforceObject<Case>(objectType);

export function caseMethods(caseBase: SalesforceObjectInterface<Case>) {
 return {
    // Add method definitions here e.g.

    // getCaseObjectByEmail: async (email: string): Promise<Case> => {
    //     return await caseBase.getObjectByField(Case.Email, email)    
    // },
    // getCaseObjectByName: async (name: string): Promise<Case> => {
    //     return await caseBase.getObjectByField(Case.Name, name)    
    // },

  };
}
